[project]
name = "python-regex-website"
version = "1.0.2"
description = "A Python web app for regex testing"
authors = [{ name = "vfedotovs", email = "vtrader@inbox.lv" }]
dependencies = []

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.2"
tag_format = "v$version"
