name: Test and Build 
on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [ '3.9', '3.10']
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_AUTH_TOKEN }}
    steps:
      - name: Checkout python-regex-website
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: env.DOCKER_LOGIN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Setup
        run: |
          sudo apt-get update
          make setup
      - name: Lint
        run: make lint
      - name: Test with pytest
        run: make test version=${{ matrix.python-version }}
      - name: Test coverage
        run:  make cov
      - name: Build docker
        run: make build
      - name: Push Docker to Dockerhub
        run: make push
